added feautre policy section
w3c/gamepad pull request #112
Opened 2019-09-23 05:19 UTC by marcoscaceres

Closes #???

Related: https://github.com/w3c/permissions/pull/200

The following tasks have been completed:

 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

2019-09-24 23:35 UTC, JamesHollyer requested changes
Gamepad events also need protection.  We should simply put something like "Events will not be fired unless the feature policy "gamepad" is enabled."

2019-09-25 07:48 UTC, marcoscaceres commented
> Gamepad events also need protection. We should simply put something like "Events will not be fired unless the feature policy "gamepad" is enabled."

good point!  I forgot they fire on the Window object.

2019-10-01 18:50 UTC, JamesHollyer commented
I would like to see an issue number that gets closed by this change.  But the change itself looks good. 
 Also fyi, I am currently implementing the metric for gamepad use in cross origin sub frames so we have more info on how to move forward with this breaking change.

2019-10-01 18:51 UTC, JamesHollyer approved these changes
I would like to see an issue number that gets closed by this change. But the change itself looks good to me.
Also fyi, I am currently implementing the metric for gamepad use in cross origin sub frames so we have more info on how to move forward with this breaking change.

2019-10-15 06:25 UTC, marcoscaceres commented
> I would like to see an issue number that gets closed by this change. 

#119 - once we have the telemetry data, we can move on the tests and implementation commitments.

2019-10-25 09:36 UTC, sidvishnoi commented on index.html
> +          A <a>document</a>’s <a>feature policy</a> determines whether any
```suggestion
          A <a>document</a>’s [=Document/feature policy=] determines whether any
```

2020-10-29 22:57 UTC, merged

2021-01-29 00:35 UTC, greggman commented
broke a few hundred or thousand games on itch.io

2021-01-29 20:51 UTC, nondebug commented
Which browser? As far as I know this change isn't enforced yet in Chrome or Firefox.

Can you link to an example of a game that was broken?

2021-01-30 04:14 UTC, greggman commented
You're right. There's just a warning. So they'll all break in a few months but not today

2021-01-30 04:31 UTC, reillyeon commented
According to [their documentation](https://itch.io/docs/creators/html5) itch.io hosts web games by embedding an iframe. This is why this change will break a number of games but also means that the fix is simple. itch.io needs to add "gamepad" to the existing `allow` attribute in the `<iframe>` tags on their pages. They already appear to allow a number of other capabilities through this attribute so it seems that they understand how Permissions Policy works. If I'm correct then this shouldn't require any changes on the part of individual game authors. The change can be made unilaterally by itch.io.

2021-02-09 10:19 UTC, subsoap commented
I have contacted the itch.io admin about this via e-mail. If the change is not done in a few days someone else should try pinging him via social media until he notices. He has been responsive about adding needed permissions before so it will likely be done before this is enforced.

2021-02-09 10:48 UTC, greggman commented
Anyone updating mdn?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy

2021-02-09 18:43 UTC, reillyeon commented
Pinging @jpmedley for the MDN update. This change hasn't shipped in Chrome or Firefox but we've started to show a console warning so a note in MDN would be helpful as well.

2021-02-10 01:59 UTC, subsoap commented
Gamepad permission has now been added to itch.io iframe. ✨

2021-02-28 18:41 UTC, byersdz commented
I've added an allow="gamepad" attribute to the iframes on https://bitmelo.com however I am still getting this warning in Chrome. Am I handling this correctly or is there something else I need to do?

2021-03-01 20:00 UTC, nondebug commented
@byersdz I tried [Katana](https://bitmelo.com/user/david/games/katana) in Chrome 88.0.4324.182 (Official Build) (64-bit) but didn't see any gamepad-related console messages. I checked the source and everything seems fine.

Can you share the text of the console warning?

2021-03-01 20:08 UTC, reillyeon commented
I saw the message when I loaded https://bitmelo.com, I think I understand the issue and have filed https://crbug.com/1183491 to track the fix.

2021-07-24 20:48 UTC, subsoap commented
Is this required yet? When adding the permission to iframes (allow="gamepad") it still prints 

> Unrecognized feature: 'gamepad'.

But it also still mentions

> VM17:1 getGamepad will now require a Permission Policy. Please update your application accordingly. For more information see https://github.com/w3c/gamepad/pull/112

Seen here in console

https://www.pixcade.com/big-klondike/

2021-07-26 04:39 UTC, marcoscaceres commented
@subsoap, I believe it should be "coming soon". @JamesHollyer, any update?

2021-09-09 23:54 UTC, marcoscaceres commented
Filed WebKit bug https://bugs.webkit.org/show_bug.cgi?id=230136 ... will implement that.